name: Deploy to staging
on:
  workflow_run:
    workflows:
      - "FAKE CI Tests"
    types:
      - completed
    branches: [ master ]
  workflow_dispatch:
  repository_dispatch:
jobs:
  get-environment-name:
    name: Get environment based on branch
    if: github.event_name != 'workflow_run' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-20.04
    outputs:
      environment: ${{ steps.extractenvironment.outputs.environment }}
    steps:
      - run: echo GITHUB_BRANCH="${GITHUB_REF##refs/heads/}" >> $GITHUB_ENV

      - id: extractenvironment
       run: |
         if [[ $GITHUB_BRANCH == 'master' ]]; then
           echo "::set-output name=environment::production"
         else
           echo "This workflow is probably running in a wrong branch"
         fi
  deploy:
    name: Deploy
    if: github.event_name != 'workflow_run' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    needs:
      - get-environment-name
    runs-on: ubuntu-20.04
    environment: ${{ needs.get-environment-name.outputs.environment }}
    env:
      ENV: ${{ secrets.ENV }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          if [[ ${{ env.ENV }} == 'production' ]]; then
            echo "It's prod indeed"
          fi
