name: Deploy to staging
on:
  workflow_run:
    workflows:
      - "FAKE CI Tests"
    types:
      - completed
    branches: [ master ]
  workflow_dispatch:
  repository_dispatch:
jobs:
  init:
    name: Set environment variable based on branch
    if: github.event_name != 'workflow_run' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-20.04
    steps:
     - run: |
         if [[ env.GITHUB_BRANCH == 'master' ]]; then
           echo "ENVIRONMENT=production" >> $GITHUB_ENV
         else
           echo "NO GO"
         fi
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    if: github.event_name != 'workflow_run' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    env:
      ENV: ${{ secrets.ENV }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          if [[ ${{ secrets.ENV }} == 'staging' ]]; then
            echo "It's *** indeed"
          fi